name = "myself-bbs"
main = "dist/worker.js"
account_id = "b1c3d1b89f9131a84a0f1f6a973232f1"
workers_dev = true
kv_namespaces = []
compatibility_date = "2022-06-01"

[build]
command = "npm run -s build"

[[rules]]
type = "ESModule"
globs = ["src/**/*.js"]
