name: Data Crawler

on:
    schedule:
        - cron: "0 */4 * * *"
    workflow_dispatch:

jobs:
    crawler:
        name: Data Crawler
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Main Branch
              uses: actions/checkout@v4

            - name: Checkout Data Branch
              uses: actions/checkout@v4
              with:
                  ref: data
                  path: file

            - uses: pnpm/action-setup@v2
              with:
                version: 8.15.8

            - name: Build Data
              run: npm run crawl

            - name: Commit
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: "./file"
                  publish_branch: "data"
